# Generated by Django 4.2.29 on 2026-04-10 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('trial_id', models.UUIDField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('trial_status', 'Trial Status Report'), ('cro_oversight', 'CRO Oversight Report'), ('regulatory_update', 'Regulatory Update'), ('executive_summary', 'Executive Summary'), ('board_update', 'Board/Investor Update'), ('enrollment_forecast', 'Enrollment Forecast')], max_length=30)),
                ('audience', models.CharField(choices=[('team', 'Internal Team'), ('executive', 'Executive Leadership'), ('board', 'Board of Directors'), ('investor', 'Investors'), ('regulatory', 'Regulatory Authority'), ('cro', 'CRO Partner')], default='team', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('data_snapshot', models.JSONField(default=dict, help_text='Structured data used to generate this report (for verification)')),
                ('generated_by', models.UUIDField(blank=True, help_text='User who triggered generation', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('feature', models.CharField(db_index=True, help_text="e.g., 'nl_query', 'status_report', 'enrollment_forecast', 'cro_scorecard'", max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('request_summary', models.TextField(blank=True, default='', help_text='Brief description of what was asked (no PII)')),
                ('response_summary', models.TextField(blank=True, default='', help_text='Brief summary of what was returned')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIWorkspaceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(unique=True)),
                ('provider', models.CharField(default='anthropic', max_length=20)),
                ('api_key_encrypted', models.TextField(blank=True, default='', help_text='Encrypted API key (use Fernet or similar)')),
                ('model', models.CharField(default='claude-sonnet-4-6', max_length=100)),
                ('monthly_token_budget', models.BigIntegerField(default=1000000)),
                ('tokens_used_this_month', models.BigIntegerField(default=0)),
                ('budget_reset_date', models.DateField(blank=True, null=True)),
                ('features_enabled', models.JSONField(default=dict, help_text='Feature flags: task_intelligence, communication_ai, enrollment_forecast, etc.')),
                ('recall_api_key_encrypted', models.TextField(blank=True, default='')),
                ('auto_join_meetings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_workspace_config',
            },
        ),
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook')], max_length=20)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('calendar_id', models.CharField(blank=True, default='primary', max_length=255)),
                ('auto_join_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_calendar_connections',
                'unique_together': {('user_id', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_url', models.URLField(max_length=512)),
                ('meeting_type', models.CharField(choices=[('cro_oversight', 'CRO Oversight Call'), ('investigator', 'Investigator Meeting'), ('regulatory', 'Regulatory Strategy'), ('internal', 'Internal Team Meeting'), ('board', 'Board/Investor Meeting'), ('other', 'Other')], default='other', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('recall_bot_id', models.CharField(blank=True, default='', help_text='Recall.ai bot instance ID', max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('bot_joining', 'Bot Joining'), ('in_progress', 'In Progress'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('decisions', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list, help_text='[{task, owner, deadline, created_issue_id}]')),
                ('attendees', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='ai.calendarconnection')),
            ],
            options={
                'db_table': 'ai_scheduled_meetings',
                'ordering': ['-start_time'],
            },
        ),
    ]
