# Generated by Django 4.2.29 on 2026-04-10 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('changed_by_user_id', models.UUIDField()),
                ('affected_user_id', models.UUIDField()),
                ('change_type', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke'), ('modify', 'Modify')], max_length=10)),
                ('role_before', models.CharField(blank=True, default='', max_length=50)),
                ('role_after', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'compliance_access_control_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('sign', 'Sign'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change')], max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='', help_text='Required for changes to regulatory records')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('previous_hash', models.CharField(blank=True, default='', help_text='SHA-256 of the previous audit record in this workspace', max_length=64)),
                ('record_hash', models.CharField(blank=True, default='', help_text="SHA-256 hash of this record's content", max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'compliance_audit_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataProcessingAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_url', models.TextField(blank=True, default='')),
                ('data_categories', models.JSONField(default=list, help_text="Categories of personal data processed: ['patient_data', 'site_staff_data', etc.]")),
                ('legal_basis', models.CharField(blank=True, default='', help_text='GDPR Article 6 legal basis for processing', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_data_processing_agreements',
            },
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('meaning', models.CharField(choices=[('approved', 'Approved'), ('reviewed', 'Reviewed'), ('authorized', 'Authorized'), ('verified', 'Verified'), ('rejected', 'Rejected')], max_length=20)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature_hash', models.CharField(help_text='SHA-256(user_id + meaning + signed_at + record content)', max_length=64)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='compliance.auditlog')),
            ],
            options={
                'db_table': 'compliance_electronic_signatures',
                'ordering': ['signed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['workspace_id', 'created_at'], name='compliance__workspa_849a68_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'record_id'], name='compliance__model_n_3998ec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id', 'created_at'], name='compliance__user_id_aadeae_idx'),
        ),
    ]
